# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RA_u19UW4CVae555Gf1hHDR_nXc7Ayn
"""

import tweepy
import time

auth = tweepy.OAuthHandler('V2oqYIT9iFBTVxRbkMDJvwk1Q', 'WKgmOaSWYmQpF4bx2Wl93PSSVaE9ZJWYY6NEoJ93lKsydWkn8b')
# consumer_key, consumer_secret
# etapa de autenticação. Essas chaves são obtidas dentro do Twitter Deveolper, "API Key" e "API Key Secret"

auth.set_access_token('1406709015967584256-uiK8ns0sZ87BnDHf6fELavpjWvv66W', 'lbFmUJUC3U4xbiRenLfCEkHeVqiTg49vgNfVKqoxqvVsi')
#key, secret

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
# esses dois parâmetros é só para executar depois que o limite dos tweets for atingido

user = api.me()

print(user)

search = 'a história vai cobrar'
numero = 30

for tweet in tweepy.Cursor(api.search, search).items(numero):
  try:
    print("nome do usuário: @", tweet.user.screen_name)
    api.update_status(status='@' + tweet.user.screen_name + " Ustra morreu de velho.")
    print('Tweet enviado corretamente')
    time.sleep(30)
  except tweepy.TweepError as error:
    print(error.reason)
  except StopIteration:
    break